name: Mirror GitHub
on:
  push:
    branches:
      - main  # trigger on push to the main branch
      - master # if i ever use master

jobs:
  mirror:
    runs-on: docker
    steps:
      - name: Checkout repository # checking out is basically just cloning
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # fetch all history for a proper force push

      - name: Modify README # not real repo, so we say its a mirror of the forgejo repo
        run: |
          echo "this repo is a mirror of [my self-hosted forgejo repo](https://185.68.244.71/dima/xkcd.sh/), please visit it" > README.md

      - name: Get latest commit message and description # ion want it to be beep boop
        run: |
          {
            echo "FULL_MSG<<EOF"
            git log -1 --pretty=%B
            echo "EOF"
          } >> "$GITHUB_ENV"

      - name: Push to GitHub # self explanatory
        env:
          GH_PAT: ${{ secrets.GH_PAT }}
        run: |
          git config --global user.name "Forgejo Bot"
          git config --global user.email "bot+not_a@real.person"
          
          # use the GH_PAT for authentication in the remote URL
          REMOTE_REPO="https://x-access-token:${GH_PAT}@github.com/IdkWhatAmIDoin/xkcd.sh.git"
          
          git add .
          git commit -m "${{ env.FULL_MSG }} [skip ci]" -m "Beep boop - I am not a real person."
          git push --mirror "$REMOTE_REPO"
